'use client'

import { useState, useRef, useEffect } from 'react'
import { createClient } from '@supabase/supabase-js'
import { GraduationCap, X, Send, Loader2, ChevronDown } from 'lucide-react'
import ReactMarkdown from 'react-markdown'

const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!)

interface Message { role: 'user' | 'assistant'; content: string }

const WELCOME = "Hey! I'm your LogiCRM assistant. I can help you use the platform, build campaigns, work your pipeline, or answer freight sales questions. What do you need?"

const HELP_DOCS = [
  { category: 'Getting Started', items: [
    { q: 'How do I import my contacts?', a: 'Go to Contacts → Import. Upload a CSV or Excel file. Map your columns and click Import. LogiCRM handles duplicates automatically.' },
    { q: 'How do I connect Outlook or Gmail?', a: 'Go to Settings → Email tab. Click Connect Gmail or Connect Outlook and follow the authorization steps. Once connected, emails sync automatically.' },
    { q: 'How do I invite a team member?', a: "Go to Settings → Team tab. Enter their email and click Invite. They'll receive a magic link to join your organization." },
  ]},
  { category: 'Campaigns', items: [
    { q: 'How do I build a campaign?', a: 'Go to Campaigns → New Campaign or use AI Sequence for a 7-touch sequence generated by AI. Choose your contacts, write your sequence, and launch to Instantly.ai.' },
    { q: 'How do I submit a campaign for approval?', a: 'Build your campaign, then click "Submit for Approval" on the campaign detail page. Your manager will review and approve or reject it.' },
    { q: 'What are merge tags?', a: 'Use {{first_name}} and {{company}} in your email body to personalize each email automatically. Do not use merge tags in subject lines.' },
  ]},
  { category: 'Contacts & Pipeline', items: [
    { q: 'How do I set a shipper tier?', a: 'Open a contact, find the Shipper Tier field, and select Small, Medium, Large, or XL based on their freight volume.' },
    { q: 'How do I log a call or activity?', a: 'Open a contact or deal and click "+ Log Activity". Choose the type (call, email, note) and add your notes.' },
    { q: 'How do I add a deal to the pipeline?', a: 'Go to Pipeline and click the + button on any stage, or open a contact and click "+ Add Deal" in the Deals card.' },
  ]},
  { category: 'Email & Outreach', items: [
    { q: 'Why do I need a separate domain for cold outreach?', a: 'Sending mass cold emails from your primary domain risks getting it flagged as spam. Use a separate outreach domain warmed up in Instantly.' },
    { q: 'How long does domain warmup take?', a: 'At least 14 days. Start slow (20 emails/day) and ramp up gradually. Instantly handles this automatically with slow ramp enabled.' },
  ]},
  { category: 'Billing', items: [
    { q: 'How do I upgrade my plan?', a: 'Go to Settings and click "Upgrade" or visit the pricing page. Plans start at $29/mo for Rep and $149/mo for Team.' },
    { q: 'How do I cancel?', a: 'Go to Settings → Billing and click Cancel Subscription. Your account remains active until the end of your billing period.' },
  ]},
]

export default function TrainingChat() {
  const [open, setOpen] = useState(false)
  const [tab, setTab] = useState<'ai' | 'docs' | 'support'>('ai')
  const [messages, setMessages] = useState<Message[]>([])
  const [input, setInput] = useState('')
  const [loading, setLoading] = useState(false)
  const [userCtx, setUserCtx] = useState<{ name: string; company: string; email: string }>({ name: '', company: '', email: '' })
  const [expandedQ, setExpandedQ] = useState<string | null>(null)
  const [supportSubject, setSupportSubject] = useState('')
  const [supportMessage, setSupportMessage] = useState('')
  const [supportSending, setSupportSending] = useState(false)
  const [supportSent, setSupportSent] = useState(false)
  const scrollRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    supabase.auth.getUser().then(async ({ data: { user } }) => {
      if (!user) return
      const name = user.user_metadata?.display_name || ''
      const res = await fetch(`/api/settings?userId=${user.id}`)
      const data = await res.json()
      setUserCtx({ name, company: data.company?.company_name || '', email: user.email || '' })
    })
  }, [])

  useEffect(() => { scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: 'smooth' }) }, [messages])

  async function handleSend() {
    if (!input.trim() || loading) return
    const userMsg: Message = { role: 'user', content: input.trim() }
    const newMessages = [...messages, userMsg]
    setMessages(newMessages)
    setInput('')
    setLoading(true)
    try {
      const res = await fetch('/api/training-chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ messages: newMessages, userContext: userCtx }) })
      const data = await res.json()
      if (data.reply) setMessages(prev => [...prev, { role: 'assistant', content: data.reply }])
    } catch { setMessages(prev => [...prev, { role: 'assistant', content: 'Sorry, something went wrong.' }]) }
    setLoading(false)
  }

  async function handleSupportSend() {
    if (!supportSubject.trim() || !supportMessage.trim()) return
    setSupportSending(true)
    try {
      await fetch('/api/support/contact', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ subject: supportSubject, message: supportMessage, userName: userCtx.name, userEmail: userCtx.email, pageUrl: typeof window !== 'undefined' ? window.location.href : '' }) })
      setSupportSent(true)
      setSupportSubject('')
      setSupportMessage('')
    } catch { /* ignore */ }
    setSupportSending(false)
  }

  const displayMessages = messages.length === 0 ? [{ role: 'assistant' as const, content: WELCOME }] : messages

  return (
    <>
      {!open && (
        <button onClick={() => setOpen(true)} className="fixed bottom-6 right-6 z-50 w-14 h-14 rounded-full flex items-center justify-center shadow-2xl hover:brightness-110 transition-all" style={{ backgroundColor: '#0f1c35', border: '2px solid #d4930e' }}>
          <GraduationCap className="w-6 h-6" style={{ color: '#d4930e' }} />
        </button>
      )}

      {open && (
        <div className="fixed bottom-6 right-6 z-50 w-[400px] h-[520px] rounded-2xl flex flex-col shadow-2xl overflow-hidden" style={{ backgroundColor: '#0f1c35', border: '1px solid rgba(212,147,14,0.3)' }}>
          {/* Header */}
          <div className="px-4 py-3 flex items-center justify-between border-b shrink-0" style={{ borderColor: 'rgba(255,255,255,0.1)' }}>
            <span className="text-sm font-semibold text-white">LogiCRM Assistant</span>
            <button onClick={() => setOpen(false)} className="text-blue-300/50 hover:text-white"><X className="w-4 h-4" /></button>
          </div>

          {/* Tabs */}
          <div className="flex border-b shrink-0" style={{ borderColor: 'rgba(255,255,255,0.1)' }}>
            {([['ai', '💬 Ask AI'], ['docs', '📚 Help'], ['support', '🎧 Support']] as const).map(([id, label]) => (
              <button key={id} onClick={() => setTab(id as typeof tab)} className={`flex-1 py-2 text-xs font-medium transition-colors ${tab === id ? 'border-b-2' : 'text-blue-300/40 hover:text-blue-300'}`} style={tab === id ? { color: '#d4930e', borderColor: '#d4930e' } : undefined}>
                {label}
              </button>
            ))}
          </div>

          {/* Content */}
          <div className="flex-1 overflow-hidden flex flex-col">

            {/* AI Tab */}
            {tab === 'ai' && (
              <>
                <div ref={scrollRef} className="flex-1 overflow-y-auto px-4 py-3 space-y-3">
                  {displayMessages.map((msg, i) => (
                    <div key={i} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                      <div className={`max-w-[85%] rounded-xl px-3 py-2 text-sm leading-relaxed ${msg.role === 'user' ? 'text-white' : 'text-blue-200 chat-markdown'}`} style={{ backgroundColor: msg.role === 'user' ? 'rgba(212,147,14,0.2)' : 'rgba(255,255,255,0.05)', ...(msg.role === 'user' ? { whiteSpace: 'pre-wrap' as const } : {}) }}>
                        {msg.role === 'user' ? msg.content : <ReactMarkdown>{msg.content}</ReactMarkdown>}
                      </div>
                    </div>
                  ))}
                  {loading && <div className="flex justify-start"><div className="rounded-xl px-3 py-2" style={{ backgroundColor: 'rgba(255,255,255,0.05)' }}><Loader2 className="w-4 h-4 animate-spin text-blue-300/50" /></div></div>}
                </div>
                <div className="px-3 py-3 border-t shrink-0" style={{ borderColor: 'rgba(255,255,255,0.1)' }}>
                  <div className="flex items-center gap-2">
                    <input type="text" value={input} onChange={e => setInput(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') handleSend() }} placeholder="Ask about LogiCRM, freight sales, or cold outreach..." className="flex-1 bg-white/5 border border-white/10 rounded-lg px-3 py-2 text-sm text-white placeholder-blue-300/30 focus:outline-none focus:ring-2 focus:ring-yellow-500/50" disabled={loading} />
                    <button onClick={handleSend} disabled={loading || !input.trim()} className="p-2 rounded-lg disabled:opacity-30 hover:brightness-110" style={{ backgroundColor: '#d4930e' }}><Send className="w-4 h-4" style={{ color: '#0f1c35' }} /></button>
                  </div>
                </div>
              </>
            )}

            {/* Help Docs Tab */}
            {tab === 'docs' && (
              <div className="flex-1 overflow-y-auto px-4 py-3 space-y-4">
                {HELP_DOCS.map(cat => (
                  <div key={cat.category}>
                    <p className="text-[10px] font-semibold uppercase tracking-wide text-blue-300/40 mb-2">{cat.category}</p>
                    <div className="space-y-1">
                      {cat.items.map(item => (
                        <div key={item.q}>
                          <button onClick={() => setExpandedQ(expandedQ === item.q ? null : item.q)} className="w-full flex items-center justify-between px-3 py-2 rounded-lg text-left hover:bg-white/5 transition-colors">
                            <span className="text-xs text-white">{item.q}</span>
                            <ChevronDown className={`w-3 h-3 text-blue-300/30 transition-transform ${expandedQ === item.q ? 'rotate-180' : ''}`} />
                          </button>
                          {expandedQ === item.q && (
                            <div className="px-3 pb-2">
                              <p className="text-xs text-blue-200/70 leading-relaxed">{item.a}</p>
                            </div>
                          )}
                        </div>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            )}

            {/* Support Tab */}
            {tab === 'support' && (
              <div className="flex-1 overflow-y-auto px-4 py-3 space-y-4">
                {supportSent ? (
                  <div className="text-center py-8">
                    <p className="text-sm text-emerald-400 font-medium mb-1">Message sent!</p>
                    <p className="text-xs text-blue-300/50">We&apos;ll get back to you within 1 business day.</p>
                    <button onClick={() => setSupportSent(false)} className="text-xs mt-3" style={{ color: '#d4930e' }}>Send another</button>
                  </div>
                ) : (
                  <>
                    <div>
                      <p className="text-xs font-semibold text-white mb-3">Send a message</p>
                      <input type="text" value={supportSubject} onChange={e => setSupportSubject(e.target.value)} placeholder="Subject" className="w-full bg-white/5 border border-white/10 rounded-lg px-3 py-2 text-xs text-white placeholder-blue-300/30 mb-2 focus:outline-none focus:ring-2 focus:ring-yellow-500/50" />
                      <textarea value={supportMessage} onChange={e => setSupportMessage(e.target.value)} placeholder="How can we help?" rows={4} className="w-full bg-white/5 border border-white/10 rounded-lg px-3 py-2 text-xs text-white placeholder-blue-300/30 mb-2 resize-none focus:outline-none focus:ring-2 focus:ring-yellow-500/50" />
                      <button onClick={handleSupportSend} disabled={supportSending || !supportSubject.trim() || !supportMessage.trim()} className="w-full py-2 rounded-lg text-xs font-semibold hover:brightness-110 disabled:opacity-40 transition-colors" style={{ backgroundColor: '#d4930e', color: '#0f1c35' }}>
                        {supportSending ? 'Sending...' : 'Send Message'}
                      </button>
                    </div>
                    <div className="border-t pt-3" style={{ borderColor: 'rgba(255,255,255,0.1)' }}>
                      <p className="text-[10px] font-semibold uppercase text-blue-300/40 mb-2">Quick Links</p>
                      <a href="mailto:rmassey@macotransport.com" className="block text-xs text-blue-300 hover:text-white py-1">📧 Email us: rmassey@macotransport.com</a>
                      <p className="text-xs text-blue-300/40 py-1">📅 Schedule a call (coming soon)</p>
                    </div>
                  </>
                )}
              </div>
            )}
          </div>
        </div>
      )}

      <style jsx global>{`
        .chat-markdown h1, .chat-markdown h2, .chat-markdown h3 { font-weight: 600; color: #fff; margin: 0.5em 0 0.25em; }
        .chat-markdown p { margin: 0.35em 0; }
        .chat-markdown ul, .chat-markdown ol { margin: 0.35em 0; padding-left: 1.25em; }
        .chat-markdown li { margin: 0.15em 0; }
        .chat-markdown strong { color: #fff; font-weight: 600; }
        .chat-markdown code { background: rgba(255,255,255,0.08); padding: 0.1em 0.3em; border-radius: 3px; font-size: 0.9em; }
        .chat-markdown a { color: #d4930e; text-decoration: underline; }
      `}</style>
    </>
  )
}
